baseURL = "https://srikanthbaride.github.io/"
languageCode = "en-us"
title = "Dr. Srikanth Baride"
theme = "ananke"
publishDir = "docs"
enableRobotsTXT = true
paginate = 10

[outputs]
home    = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy= ["HTML", "RSS"]
term    = ["HTML", "RSS"]

[params]
  author = "Srikanth Baride"
  description = "Postdoctoral Researcher at USD • Reinforcement Learning, World Models, Data Mining"
  github = "https://github.com/srikanthbaride"
  linkedin = "https://www.linkedin.com/in/srikanth-baride/"
  email = "srikanth.baride@usd.edu"
  favicon = "img/favicon.png"

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url  = "/publications/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 4
  [[menu.main]]
    name = "Teaching"
    url  = "/teaching/"
    weight = 5
  [[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6
